apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.openslice.service: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: activemq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/back: "true"
        io.openslice.service: activemq
    spec:
      containers:
        - image: webcenter/activemq:5.14.3
          name: anactivemq
          ports:
            - containerPort: 8161
          resources: {}
      restartPolicy: Always
status: {}
