apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: bugzilla-client
  name: bugzilla-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bugzilla-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/back: "true"
        io.kompose.network/front: "true"
        io.kompose.service: bugzilla-client
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.activemq.brokerUrl": "tcp://activemq:61616", "spring.activemq.user": "admin", "spring.activemq.password": "adminx", "spring.cloud.consul.host": "http://consul:8500", "spring.cloud.consul.discovery.healthCheckUrl" : "http://bugzilla-client:13010/actuator/health", "bugzillaurl":"example.com:443/bugzilla", "bugzillakey":"VH2Vw0iI5aYgALFFzVDWqhACwt6Hu3bXla9kSC1Z", "main_operations_product":"My Operations" }'
          image: openslice/io.openslice.bugzilla:latest
          name: bugzilla-client
          ports:
            - containerPort: 13010
          resources: {}
      restartPolicy: Always
status: {}
