apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.openslice.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/back: "true"
        io.kompose.network/front: "true"
        io.openslice.service: keycloak
    spec:
      initContainers:
      - name: init-mysql-portal
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql-portal; do echo waiting for mysql-portal; sleep 2; done"]
      
      containers:
        - env:
            - name: DB_ADDR
              value: mysql-portal
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: keycloak
            - name: DB_VENDOR
              value: MYSQL
            - name: JAVA_OPTS
              value: -server -Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:+UseAdaptiveSizePolicy -XX:MaxMetaspaceSize=1024m -Dkeycloak.frontendUrl=http://10.10.10.35/auth -Djava.net.preferIPv4Stack=true -Djboss.as.management.blocking.timeout=3600
            - name: JDBC_PARAMS
              value: useSSL=false
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm-export.json
            - name: KEYCLOAK_PASSWORD
              value: Pa55w0rd
            - name: KEYCLOAK_USER
              value: admin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          image: quay.io/keycloak/keycloak:11.0.3
          name: keycloak
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
          - name: "keycloak-configuration"
            readOnly: true
            mountPath: "/tmp"
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
      volumes:
        - name: "keycloak-configuration"
          configMap:
            name: keycloak-realm-config
status: {}
