apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: keycloak
  name: keycloak
  namespace: openslice
spec:
  ports:
    - name: "8080"
      port: 8080
    - name: "8443"
      port: 8443
  selector:
    io.openslice.service: keycloak
status:
  loadBalancer: {}
