apiVersion: v1
kind: PersistentVolume
metadata:
  name: os-activemq-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/openslice/activemq"
---

