apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-activemq
  name: {{ .Release.Name }}-activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-activemq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-activemq
    spec:
      containers:
        - image: webcenter/activemq:5.14.3
          name: {{ .Release.Name }}-activemq
          ports:
            - containerPort: 8161
          resources: {}
      restartPolicy: Always
status: {}
