apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-activemq
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-activemq
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-activemq      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-activemq
    spec:
      containers:
          image: "{{ .Values.image.activemq.repository }}:{{ .Values.image.activemq.tag | default .Chart.AppVersion }}"
          name: {{ .Release.Name }}-activemq
          ports:
            - containerPort: 8161
          resources: {}
      restartPolicy: Always
status: {}
