apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: openslice
  creationTimestamp: null
  name: back
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/back: "true"
  podSelector:
    matchLabels:
      io.kompose.network/back: "true"
