apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-bugzilla-client
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: bugzilla-client
spec:
  ports:
    - name: "13010"
      port: 13010
  selector:
    io.openslice.service: {{ .Release.Name }}-bugzilla-client
status:
  loadBalancer: {}
