apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-bugzilla-client
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-bugzilla-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-bugzilla-client
  strategy: {}
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-bugzilla-client
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.activemq.brokerUrl": "tcp://{{ .Release.Name }}-activemq:61616", "spring.activemq.user": "{{.Values.oscreds.activemq_user}}", "spring.activemq.password": "{{.Values.oscreds.activemq_pass}}", "spring.cloud.consul.host": "http://{{ .Release.Name }}-consul:8500", "spring.cloud.consul.discovery.healthCheckUrl" : "http://{{ .Release.Name }}-bugzilla-client:13010/actuator/health", "bugzillaurl":"{{ .Values.bugzillaurl }}", "bugzillakey":"{{ .Values.bugzillakey }}", "main_operations_product":"{{ .Values.main_operations_product }}" }'
          image: {{ .Values.image.bugzillaclient.repository }}:{{ .Values.image.bugzillaclient.tag }}
          name: {{ .Release.Name }}-bugzilla-client
          ports:
            - containerPort: 13010
          resources: {}
      restartPolicy: Always
status: {}
