apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-centrallog
  name: centrallog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-centrallog
  strategy: {}
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-centrallog
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.activemq.brokerUrl": "tcp://{{ .Release.Name }}-activemq:61616", "spring.activemq.user": "{{.Values.oscreds.activemq_user}}", "spring.activemq.password": "{{.Values.oscreds.activemq_pass}}", "spring.cloud.consul.host": "http://{{ .Release.Name }}-consul:8500", "spring.cloud.consul.discovery.healthCheckUrl" : "http://{{ .Release.Name }}-centrallog:13013/actuator/health", "centrallogurl":"{{centrallogurl}}" }'
          image: image: "{{ .Values.image.centrallog.repository }}:{{ .Values.image.centrallog.tag | default .Chart.AppVersion }}"
          name: {{ .Release.Name }}-centrallog
          ports:
            - containerPort: 13013
          resources: {}
      restartPolicy: Always
status: {}
