apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-consul
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  ports:
    - name: '8500'
      port: 8500
      targetPort: 8500
    - name: '8600'
      port: 8600
      targetPort: 8600
  selector:
    io.openslice.service: {{ .Release.Name }}-consul
