apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-consul
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-consul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.openslice.service: {{ .Release.Name }}-consul
    spec:
      containers:
        - image: consul
          name: {{ .Release.Name }}-consul
          ports:
            - containerPort: 8500
            - containerPort: 8600
          resources: {}
      restartPolicy: Always
