apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-keycloak
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-keycloak
spec:
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/back: "true"
        io.kompose.network/front: "true"
        io.openslice.service: {{ .Release.Name }}-keycloak
    spec:
      initContainers:
      - name: init-mysql-portal
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-mysql; do echo waiting for {{ .Release.Name }}-mysql; sleep 2; done"]
      
      containers:
        - env:
            - name: DB_ADDR
              value: {{ .Release.Name }}-mysql
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              value: {{.Values.oscred.keycloakdbpassword}}
            - name: DB_USER
              value: keycloak
            - name: DB_VENDOR
              value: MYSQL
            - name: JAVA_OPTS
              value: -server -Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:+UseAdaptiveSizePolicy -XX:MaxMetaspaceSize=1024m -Djava.net.preferIPv4Stack=true -Djboss.as.management.blocking.timeout=3600
            - name: JDBC_PARAMS
              value: useSSL=false
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm-export.json
            - name: KEYCLOAK_PASSWORD
              value: {{.Values.oscred.keycloakadminpassword}}
            - name: KEYCLOAK_USER
              value: admin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          image: {{ .Values.image.keycloak.repository }}:{{ .Values.image.keycloak.tag }}
          name: {{ .Release.Name }}-keycloak
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
          - name: "keycloak-configuration"
            readOnly: true
            mountPath: "/tmp"
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
      volumes:
        - name: "keycloak-configuration"
          configMap:
            name: {{ .Release.Name }}-keycloak-realm-config
status: {}
