apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-keycloak
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-keycloak
spec:
  ports:
    - name: "8080"
      port: 8080
    - name: "8443"
      port: 8443
  selector:
    io.openslice.service: {{ .Release.Name }}-keycloak
status:
  loadBalancer: {}
