apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-mysql-claim0
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name:  {{ .Release.Name }}-mysql-claim0
spec:
  storageClassName: mysql-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
