apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-mysql-portal
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: mysql-portal
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    io.openslice.service: {{ .Release.Name }}-mysql-portal
status:
  loadBalancer: {}
