apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-mysql
  name: {{ .Release.Name }}-mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    io.openslice.service: {{ .Release.Name }}-mysql
status:
  loadBalancer: {}
