apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osom
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-osom
spec:
  ports:
    - name: "13100"
      port: 13100
      targetPort: 13100
  selector:
    io.openslice.service: {{ .Release.Name }}-osom
status:
  loadBalancer: {}
