apiVersion: v1
kind: Service
metadata:
  namespace: openslice
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.openslice.service: osportalapi
  name: osportalapi
spec:
  ports:
    - name: "13000"
      port: 13000
  selector:
    io.openslice.service: osportalapi
status:
  loadBalancer: {}
