apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osportalapi
  name: {{ .Release.Name }}-osportalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-osportalapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-osportalapi
    spec:
      initContainers:
      - name: init-keycloak
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-keycloak; do echo waiting for {{ .Release.Name }}-keycloak; sleep 2; done"]
      - name: init-mysql-portal
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-mysql; do echo waiting for {{ .Release.Name }}-mysql; sleep 2; done"]
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.datasource.url": "jdbc:mysql://{{ .Release.Name }}-mysql/osdb?createDatabaseIfNotExist=true", "spring.datasource.username":"root", "spring.datasource.password":"{{.Values.oscreds.mysqlpassword}}", "keycloak-internal-auth-server-url": "http://{{ .Release.Name }}-keycloak/auth", "keycloak-admin-password": "{{.Values.oscreds.keycloakdbpassword}}", "keycloak.auth-server-url": "{{ .Values.rooturl }}/auth", "spring.activemq.brokerUrl": "tcp://{{ .Release.Name }}-activemq:61616", "spring.activemq.user": "{{.Values.oscreds.activemq_user}}", "spring.activemq.password": "{{.Values.oscreds.activemq_pass}}", "spring.cloud.consul.host": "http://{{ .Release.Name }}-consul", "spring.cloud.consul.discovery.healthCheckUrl" : "http://{{ .Release.Name }}-osportalapi/osapi/actuator/health", "swagger.authserver" : "{{ .Values.rooturl }}/auth/realms/openslice", "swagger.clientid" : "osapiWebClientId", "swagger.clientsecret" : "secret", "logging.level.org.springframework" : "INFO" }'
          image: "{{ .Values.image.portalapi.repository }}:{{ .Values.image.portalapi.tag | default .Chart.AppVersion }}"
          name: {{ .Release.Name }}-openslice-portalapi
          ports:
            - containerPort: 13000
          resources: {}
          volumeMounts:
            - mountPath: /root
              name: {{ .Release.Name }}-osportalapi-claim0
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-osportalapi-claim0
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-osportalapi-claim0
status: {}
