apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osportalapi
  name: {{ .Release.Name }}-osportalapi
spec:
  ports:
    - name: "13000"
      port: 13000
  selector:
    io.openslice.service: {{ .Release.Name }}-osportalapi
status:
  loadBalancer: {}
