apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osportalapi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: osportalapi
spec:
  ports:
    - name: "13000"
      port: 13000
  selector:
    io.openslice.service: {{ .Release.Name }}-osportalapi
status:
  loadBalancer: {}
