apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osportalapi-claim0
  name: {{ .Release.Name }}-osportalapi-claim0
spec:
  storageClassName: osportalapi-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
