apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osscapi-claim0
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-osscapi-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
