apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osscapi
  name: {{ .Release.Name }}-osscapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-osscapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-osscapi
    spec:
      initContainers:
      - name: init-keycloak
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-keycloak; do echo waiting for {{ .Release.Name }}-keycloak; sleep 2; done"]
      - name: init-mysql-portal
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Release.Name }}-mysql; do echo waiting for {{ .Release.Name }}-mysql; sleep 2; done"]
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.datasource.url": "jdbc:mysql://{{ .Release.Name }}-mysql/ostmfdb?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username":"root", "spring.datasource.password":"letmein", "keycloak-internal-auth-server-url": "http://{{ .Release.Name }}-keycloak:8080/auth", "keycloak-admin-password": "Pa55w0rd", "keycloak.auth-server-url": "http://{{ .Release.Name }}-keycloak:8080/auth", "spring.activemq.brokerUrl": "tcp://{{ .Release.Name }}-activemq:61616", "spring.activemq.user": "admin", "spring.activemq.password": "adminx", "spring.cloud.consul.host": "http://{{ .Release.Name }}-consul:8500", "spring.cloud.consul.discovery.healthCheckUrl" : "http://{{ .Release.Name }}-osscapi:13082/osapi/actuator/health", "swagger.authserver" : "http://INGRESSADDR/auth/realms/openslice", "swagger.clientid" : "osapiWebClientId", "swagger.clientsecret" : "secret", "logging.level.org.springframework" : "INFO" }'
          image: "{{ .Values.image.tmfapi.repository }}:{{ .Values.image.tmfapi.tag | default .Chart.AppVersion }}"
          name: openslice-scapi
          ports:
            - containerPort: 13082
          resources: {}
          volumeMounts:
            - mountPath: /root
              name: {{ .Release.Name }}-osscapi-claim0
          readinessProbe:
            httpGet:
              path: /tmf-api/serviceCatalogManagement/v4/serviceCatalog
              port: 13082
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-osscapi-claim0
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-osscapi-claim0
status: {}
