apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-osscapi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: osscapi
spec:
  ports:
    - name: "13082"
      port: 13082
      targetPort: 13082
  selector:
    io.openslice.service: {{ .Release.Name }}-osscapi
status:
  loadBalancer: {}
