apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-portalweb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-portalweb
spec:
  ports:
    - name: "portalwebport"
      port: 80
  selector:
    io.openslice.service: {{ .Release.Name }}-portalweb
status:
  loadBalancer: {}
