apiVersion: apps/v1 
kind: Deployment 
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-portalweb
  name: {{ .Release.Name }}-portalweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-portalweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-portalweb
    spec:
      containers:
        - name: {{ .Release.Name }}-portalweb
          image: "{{ .Values.image.portalweb.repository }}:{{ .Values.image.portalweb.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: "portalweb-configuration"
            mountPath: /usr/share/nginx/html/nfvportal/js/config.js
            subPath: config.js
      volumes:
        - name: "portalweb-configuration"
          configMap:
            name: {{ .Release.Name }}-portalweb-config
            defaultMode: 420
      restartPolicy: Always
status: {}
