apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.openslice.service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/front: "true"
        io.openslice.service: portainer
    spec:
      containers:
        - image: portainer/portainer
          name: portainer
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: portainer-claim0
            - mountPath: /data
              name: portainer-data
      restartPolicy: Always
      volumes:
        - name: portainer-claim0
          persistentVolumeClaim:
            claimName: portainer-claim0
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-data
status: {}
