kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-tmfweb-config
data:
  config.prod.json: |+
    {
        "TITLE": "Openslice K8S demo",
        "PORTALVERSION":"1.0.2-SNAPSHOT",
        "WIKI": "http://INGRESSADDR",
        "BUGZILLA": "https://INGRESSADDR/bugzilla/",
        "STATUS": "http://INGRESSADDR/status/",
       "WEBURL": "http://INGRESSADDR",
        "APIURL": "http://INGRESSADDR/osapi/",
        "APITMFURL": "http://INGRESSADDR/tmf-api",
        "OAUTH_CONFIG" : {
            "issuer": "http://INGRESSADDR/auth/realms/openslice/protocol/openid-connect/auth",
            "loginUrl": "http://INGRESSADDR/auth/realms/openslice/protocol/openid-connect/auth",
            "tokenEndpoint": "http://INGRESSADDR/auth/realms/openslice/protocol/openid-connect/token",
            "redirectUri": "http://INGRESSADDR/services/services_marketplace",
            "logoutUrl": "http://INGRESSADDR/auth/realms/openslice/protocol/openid-connect/logout",
            "postLogoutRedirectUri": "http://INGRESSADDR/services/services_marketplace",
            "responseType": "code",
            "oidc": false,
            "clientId": "osapiWebClientId",
            "dummyClientSecret": "secret",
            "requireHttps": false,
            "useHttpBasicAuth": true,
            "clearHashAfterLogin": false,
            "showDebugInformation": true
        }
    }
