kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-tmfweb-config
data:
  config.prod.json: |+
    {
        "TITLE": "Openslice",
        "PORTALVERSION":"1.1.0-SNAPSHOT",
        "WIKI": "{BASEURL}/wiki",
        "BUGZILLA": "{BASEURL}/bugzilla/",
        "STATUS": "{BASEURL}/status/",
       "WEBURL": "{BASEURL}",
        "APIURL": "{BASEURL}/osapi/",
        "APITMFURL": "{BASEURL}/tmf-api",
        "OAUTH_CONFIG" : {
            "issuer": "{BASEURL}/auth/realms/openslice/protocol/openid-connect/auth",
            "loginUrl": "{BASEURL}/auth/realms/openslice/protocol/openid-connect/auth",
            "tokenEndpoint": "{BASEURL}/auth/realms/openslice/protocol/openid-connect/token",
            "redirectUri": "{BASEURL}/services/services_marketplace",
            "logoutUrl": "{BASEURL}/auth/realms/openslice/protocol/openid-connect/logout",
            "postLogoutRedirectUri": "{BASEURL}/services/services_marketplace",
            "responseType": "code",
            "oidc": false,
            "clientId": "osapiWebClientId",
            "dummyClientSecret": "secret",
            "requireHttps": false,
            "useHttpBasicAuth": true,
            "clearHashAfterLogin": false,
            "showDebugInformation": true
        }
    }
