apiVersion: v1
kind: Service
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-tmfweb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: tmfweb
spec:
  ports:
    - name: "tmwebport"
      port: 80
  selector:
    io.openslice.service: {{ .Release.Name }}-tmfweb
status:
  loadBalancer: {}
