apiVersion: apps/v1 
kind: Deployment 
metadata:
  labels:
    io.openslice.service: {{ .Release.Name }}-tmfweb
  name: tmfweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: {{ .Release.Name }}-tmfweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.openslice.service: {{ .Release.Name }}-tmfweb
    spec:
      containers:
        - name: {{ .Release.Name }}-openslice-tmfweb
          image: "{{ .Values.image.tmfweb.repository }}:{{ .Values.image.tmfweb.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: "tmfweb-configuration"
            readOnly: true
            mountPath: "/usr/share/nginx/html/services/assets/config"
      volumes:
        - name: "tmfweb-configuration"
          configMap:
            name: {{ .Release.Name }}-tmfweb-config
      restartPolicy: Always
status: {}
